language: python

python:
  - "3.7"

script:
   # Set up conda
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f environment-dev.yml
  - conda activate fire-dev
  - sphinx-build -b html ./docs ./docs/_build
  # GitHub pages ignores folder starting with _, can be avoid by
  # adding a .nojekyll file
  - touch ./docs/_build/.nojekyll

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  cleanup: false
  local_dir: docs/_build/
  name: FIRE
  email: fire@sdfe.dk
  keep_history: false
  commit_message: Deploy %{project_name} to %{url}:%{target_branch} [skip ci]
  edge: true
  on:
      branch: master
