name: fire
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cx_oracle=7.0
  - sqlalchemy=1.2.13
  - qgis=3.10
  - click
  - colorama
  - pyproj
  - pandas=1.1.2
  - xlsxwriter
  - xlrd=1.2.0
  - xmltodict
  - gama=2.13
